version: 2

sources:
  - name: grand_galleria
    database: team4-499806
    schema: grand_galleria

    tables:
      - name: data1
      - name: data2
      - name: data3
      - name: data4

models:
  - name: stg_grand_galleria__data3
    description: "Cleaned staging model for Data3"
    columns:
      - name: magaza_id
        tests:
          - not_null
      - name: tarih
        tests:
          - not_null
      - name: satis_adedi
        tests:
          - not_null

  - name: int_grand_galleria__data3_kpis
    description: "KPI calculations for Data3"

  - name: mart_grand_galleria__data3_store_performance
    description: "Store level performance metrics for Data3"
    columns:
      - name: magaza_id
        tests:
          - not_null
      - name: toplam_ciro
        tests:
          - not_null

  - name: mart_grand_galleria__data1_store_performance
    description: "Store and location level performance metrics for Data1"
    columns:
      - name: Magaza
        tests:
          - not_null

      - name: Magaza_Lokasyon
        tests:
          - not_null

      - name: toplam_ciro
        tests:
          - not_null

      - name: toplam_satis_adedi
        tests:
          - not_null

      - name: toplam_stok_adedi
        tests:
          - not_null

      - name: toplam_stok_tutari
        tests:
          - not_null   